### ISSUE TITLE
Don't think that the title drop down search is rebuilding properly.

### ISSUE THREAD

**Issue by CathyHajo** [JonathanReeve/sanger#93] opened 2015-07-23 18:56 UTC
There are a number of errors in the title drop-down search, but when I correct the document, commit the changes, sync with the server and rebuild and reparse, they are not going away. Some of them (French ones) are coming up from a portion of Magnetation Methods of Birth Control, where we deleted a large chunk of the document with a French bibliography. The search tells me that the title (Auyons ....) is in Magnetation, but when I look at the document on the screen, it is the correct, shorter version that doesn't have this text.

**Comment by JonathanReeve** [comment] 2015-08-01 23:31
Looking into this. Duplicate of #84.

**Closed by JonathanReeve** 2015-08-01 23:31 UTC
